test-suite = "{{ manifest_dir }}/testcases/{{ bin_alias }}.yml"

[template]
src = '''
fn main() {
}
'''

[template.new]
edition = "2021"
dependencies = '''
proconio = { version = "=0.4.5", features = ["derive"] }
itertools = "=0.11.0"
itertools-num = "=0.1.3"
'''

[new]
kind = "cargo-compete"
platform = "atcoder"
path = "./{{ contest }}"

[test]
toolchain = "1.70.0"

[submit]
kind = "command"
args = ["cargo", "equip", "--exclude-atcoder-202301-crates", "--exclude", "proconio", "itertools", "--remove", "docs", "--minify", "libs", "--bin", "{{ bin_name }}"]
language_id = "5054" # Atcoder 202301

