# See: https://github.com/marketplace/actions/build-and-push-docker-images

name: "Rust: Build an image and deploy it to DockerHub"

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./rust/infra
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust-cp-workspace:latest
